#! /bin/bash

PSQL="psql --username=freecodecamp --dbname=periodic_table -t --no-align -c"

if [[ $1 ]]
then

  ASKED=$1

  if [[ "$ASKED" =~ ^[0-9]+$ ]]
  then
    ATOMIC_NUMBER=$($PSQL "SELECT atomic_number FROM elements WHERE atomic_number=$ASKED;")
    #echo "$ATOMIC_NUMBER"
  else
    ATOMIC_NUMBER=$($PSQL "SELECT atomic_number FROM elements WHERE symbol='$ASKED' OR name='$ASKED';")
    #echo "$ATOMIC_NUMBER"
  fi

  if [[ -z $ATOMIC_NUMBER ]]
  then
    echo "I could not find that element in the database."
  else

    $PSQL "SELECT symbol, name, atomic_mass, melting_point_celsius, boiling_point_celsius,type FROM elements INNER JOIN properties ON elements.atomic_number=properties.atomic_number INNER JOIN types ON properties.type_id = types.type_id WHERE properties.atomic_number=$ATOMIC_NUMBER;" |
    while IFS='|' read SYMBOL NAME MASS MELTING_P BOILING_P TYPE
    do
      SYMBOL=$(echo "$SYMBOL" | xargs)
      NAME=$(echo "$NAME" | xargs)
      MASS=$(echo "$NAME" | xargs)
      MELTING_P=$(echo "$MELTING_P" | xargs)
      BOILING_P=$(echo "$BOILING_P" | xargs)
      TYPE=$(echo "$TYPE" | xargs)

      echo "The element with atomic number $ATOMIC_NUMBER is $NAME ($SYMBOL). It's a $TYPE, with a mass of $MASS amu. $NAME has a melting point of $MELTING_P celsius and a boiling point of $BOILING_P celsius."
    done
  fi
else
  echo "Please provide an element as an argument."
fi
